version: 2.2.0

client:
  organization: Org4
  logging:
    level: info
  cryptoconfig:
    path: ./crypto
  credentialStore:
    path: ./crypto
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

channels:
  mychannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org4.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

organizations:
  Org4:
    users:
      User1:
        key:
          path: ./crypto/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore/key.pem
        cert:
          path: ./crypto/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/signcerts/cert.pem
    mspid: Org4MSP
    cryptoPath: ./crypto/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp
    peers:
      - peer0.org4.example.com
  ordererorg:
    mspID: OrdererMSP
    cryptoPath: ./crypto/ordererOrganizations/example.com/users/Admin@example.com/msp

orderers:
  orderer.example.com:
    url: grpcs://192.168.1.81:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ./crypto/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org4.example.com:
    url: grpcs://192.168.1.81:11051
    grpcOptions:
      ssl-target-name-override: peer0.org4.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ./crypto/peerOrganizations/org4.example.com/tlsca/tlsca.org4.example.com-cert.pem

entitymatchers:
  peer:
    - pattern: (\w*)peer0.org4.example.com(\w*)
      urlsubstitutionexp: grpcs://192.168.1.81:11051
      ssltargetoverrideurlsubstitutionexp: peer0.org4.example.com
      mappedhost: peer0.org4.example.com
  orderer:
    - pattern: (\w*)orderer.example.com(\w*)
      urlsubstitutionexp: grpcs://192.168.1.81:7050
      ssltargetoverrideurlsubstitutionexp: orderer.example.com
      mappedhost: orderer.example.com